### ISSUE TITLE
django 3.0 Incompatibility - "Invalid template library specified. ImportError raised when trying to load 'django_hosts.templatetags.hosts': cannot import name 'six' from 'django.utils'"

### ISSUE THREAD

**Issue by Farcorn** [jazzband/django-hosts#105] opened 2019-12-04 18:21 UTC
I upgraded to Django 3.0 and on runserver this error is thrown

> django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'django_hosts.templatetags.hosts': cannot import name 'six' from 'django.utils' (/Users/OHEMENGTUTU/Dropbox/Asoriba/TECH/CODEBASE/AsoribaAPI/lib/python3.7/site-packages/django/utils/__init__.py)

I think it has to do with Django 3.0 dropping dependency "six"

**Comment by 33911628** [comment] 2019-12-07 08:02
You just need to delete the places where the sixs are used.

**Comment by jar3b** [comment] 2019-12-14 21:09
Same error for me after upgrade to Django 3.0. 

Possible solutions are:
1. Use `import six` instead of `from django.utils import six` in [resolvers.py](https://github.com/jazzband/django-hosts/blob/master/django_hosts/resolvers.py#L14) and [templatetags/hosts.py](https://github.com/jazzband/django-hosts/blob/master/django_hosts/templatetags/hosts.py#L6)
2. Use failback imports for these `six` imports
3. Switch to using direct implementation of `six.iteritems(**kw)` - this is `iter(d.items(**kw))` as described [here](https://github.com/benjaminp/six/blob/master/six.py#L588), but if you do this, you will loose python2 support.

Also, after fixing this issue, new problem was arrived - import error for `django.utils.lru_cache.lru_cache` in [resolvers.py](https://github.com/jazzband/django-hosts/blob/master/django_hosts/resolvers.py#L17). Solution may be similar to previous - fixing import to `from functools import lru_cache` (due to changes described [in official django 3.0 release notes](https://docs.djangoproject.com/en/3.0/releases/3.0/)
```
Removed private Python 2 compatibility APIs
...
django.utils.lru_cache.lru_cache() - Alias of functools.lru_cache().
...
```
)

For myself i choose the second solution (failback imports) but i don't sure if that's a best decision. But if so, i can provide a PR.

**Comment by idrishmakda52** [comment] 2020-01-13 05:13
thank you  using 1 answer it works

**Comment by timgraham** [comment] 2020-01-21 14:48
duplicate of https://github.com/jazzband/django-hosts/issues/98

**Closed by timgraham** 2020-01-21 14:48 UTC

**Comment by Virsail** [comment] 2020-10-30 16:03
same error
